version: '2'
services:

  consul:
    image: "consul"
    hostname: "infrastructure.helixalpha.com"
    command: "agent -bind=165.227.3.39 -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    volumes:
      - /root/consul:/consul/data
    environment:
      VIRTUAL_HOST: infrastructure.helixalpha.com,consul.helixalpha.com
      VIRTUAL_PORT: 8500
      LETSENCRYPT_HOST: infrastructure.helixalpha.com,consul.helixalpha.com
      LETSENCRYPT_EMAIL: admin@helixalpha.com

  vault:
    depends_on:
      - consul
    image: "vault"
    hostname: "vault.infrastructure.helixalpha.com"
    links:
      - "consul:consul"
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - ./tools/wait-for-it.sh:/wait-for-it.sh:z
      - ./config/vault:/config:z
      - ./config/vault/policies:/policies:z
      - /root/vault:/vault
    entrypoint: /wait-for-it.sh -t 20 -h consul -p 8500 -s -- vault server -config=/config/with-consul.hcl

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/htpasswd:/etc/nginx/htpasswd
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - /var/www/html:/usr/share/nginx/html
      - /etc/nginx/dhparam:/etc/nginx/dhparam
      - /certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    volumes_from:
      - nginx-proxy
    volumes:
      - /certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost: